// <auto-generated />
using System;
using ConversorMoedas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConversorMoedas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923193142_AdicionaTabUsers")]
    partial class AdicionaTabUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("ConversorMoedas.Models.Conversao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataConversao")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoedaDestino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoedaOrigem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Resultado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxaUsada")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conversoes");
                });

            modelBuilder.Entity("ConversorMoedas.Models.Moeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Taxa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moedas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "USD",
                            Nome = "Dólar Americano",
                            Taxa = 1.0m,
                            UltimaAtualizacao = new DateTime(2026, 9, 23, 16, 31, 42, 241, DateTimeKind.Local).AddTicks(5562)
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "BRL",
                            Nome = "Real Brasileiro",
                            Taxa = 5.0m,
                            UltimaAtualizacao = new DateTime(2026, 9, 23, 16, 31, 42, 241, DateTimeKind.Local).AddTicks(5578)
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "EUR",
                            Nome = "Euro",
                            Taxa = 0.92m,
                            UltimaAtualizacao = new DateTime(2026, 9, 23, 16, 31, 42, 241, DateTimeKind.Local).AddTicks(5579)
                        });
                });

            modelBuilder.Entity("ConversorMoedas.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
